export const questions = [
  {
    type: 'mcq',
    text: 'Who developed the lambda calculus in the 1930s?',
    options: ['John McCarthy', 'Peter Landin', 'Alonzo Church', 'Robin Milner'],
    answer: 2,
    explanation: 'Alonzo Church developed the lambda calculus in the 1930s — a simple but powerful theory of functions that underpins Haskell.',
  },
  {
    type: 'tf',
    text: 'Lisp was the first pure functional language (no variable assignments).',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. Lisp (John McCarthy, 1950s) retained variable assignments. ISWIM (Peter Landin, 1960s) was the first pure functional language.',
  },
  {
    type: 'mcq',
    text: 'Which language introduced type inference and polymorphic types?',
    options: ['FP', 'ISWIM', 'Miranda', 'ML'],
    answer: 3,
    explanation: 'ML, developed by Robin Milner and others in the 1970s, introduced type inference and polymorphic types, making it the first modern functional language.',
  },
  {
    type: 'mcq',
    text: 'In what year was Haskell development initiated by an international committee?',
    options: ['1975', '1983', '1987', '2003'],
    answer: 2,
    explanation: 'In 1987, an international committee initiated Haskell as a standard lazy pure functional language. The Haskell 98 report was published in 2003.',
  },
  {
    type: 'tf',
    text: 'Haskell is a lazy, pure, functional language.',
    options: ['True', 'False'],
    answer: 0,
    explanation: 'True. Haskell is precisely described as Lazy (evaluates only when needed), Pure (no side effects), and Functional (computation via function application).',
  },
  {
    type: 'mcq',
    text: 'Given `omit x = 0` and `keep_going x = keep_going (x+1)`, what does `omit (keep_going 1)` return?',
    options: ['Loops forever', 'Error', '1', '0'],
    answer: 3,
    explanation: 'Because Haskell is lazy (call-by-need), `keep_going 1` is never evaluated since `omit` ignores its argument. The result is just 0.',
  },
  {
    type: 'mcq',
    text: 'Which property means an expression always yields the same value and can be replaced by that value?',
    options: ['Lazy evaluation', 'Pattern matching', 'Referential transparency', 'Immutability'],
    answer: 2,
    explanation: 'Referential transparency: if y = f x and g = h y y, then g = h (f x) (f x) produces the same result. Expressions can always be substituted with their value.',
  },
  {
    type: 'tf',
    text: 'In Haskell, `a = 1; a = 2` (reassigning a variable) is legal.',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. Haskell has immutable data. Destructive assignment is illegal — altered copies are created instead of mutating the original.',
  },
  {
    type: 'mcq',
    text: 'What does `head [1,2,3,4,5]` return?',
    options: ['[2,3,4,5]', '[1,2,3,4]', '5', '1'],
    answer: 3,
    explanation: '`head` selects the first element of a list. `head [1,2,3,4,5]` returns 1.',
  },
  {
    type: 'mcq',
    text: 'What does `[1,2,3,4,5] !! 2` return?',
    options: ['1', '2', '3', '5'],
    answer: 2,
    explanation: '`!!` is 0-indexed element access. Index 2 gives the third element: 3.',
  },
  {
    type: 'mcq',
    text: 'What does `drop 3 [1,2,3,4,5]` return?',
    options: ['[1,2,3]', '[4,5]', '[3,4,5]', '[1,2]'],
    answer: 1,
    explanation: '`drop 3` removes the first 3 elements, leaving [4,5].',
  },
  {
    type: 'mcq',
    text: 'What does `take 3 [1,2,3,4,5]` return?',
    options: ['[3,4,5]', '[1,2]', '[1,2,3]', '[2,3,4]'],
    answer: 2,
    explanation: '`take 3` selects the first 3 elements: [1,2,3].',
  },
  {
    type: 'tf',
    text: 'Function application has the LOWEST precedence in Haskell.',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. Function application has the HIGHEST precedence. So `square 2 + 3` means `(square 2) + 3`, not `square (2+3)`.',
  },
  {
    type: 'mcq',
    text: 'What does the `$` operator do in Haskell?',
    options: [
      'String concatenation',
      'Lowest precedence — eliminates parentheses',
      'Highest precedence — forces evaluation',
      'Integer division',
    ],
    answer: 1,
    explanation: '`$` has the lowest precedence. `sum ([1..5] ++ [6..10])` can be written as `sum $ [1..5] ++ [6..10]`.',
  },
  {
    type: 'mcq',
    text: 'How is the mathematical `f(g(x))` written in Haskell?',
    options: ['f(g(x))', 'f . g x', 'f (g x)', 'f{g{x}}'],
    answer: 2,
    explanation: 'Haskell uses spaces for function application. `f(g(x))` becomes `f (g x)` — parentheses are only needed for grouping.',
  },
  {
    type: 'tf',
    text: 'In Haskell, writing `x \\`div\\` y` is equivalent to `div x y`.',
    options: ['True', 'False'],
    answer: 0,
    explanation: 'True. Backtick syntax turns any two-argument function into an infix operator. `x \\`div\\` y` is syntactic sugar for `div x y`.',
  },
  {
    type: 'mcq',
    text: 'Which GHCi command reloads the currently loaded script?',
    options: [':load', ':refresh', ':reset', ':reload'],
    answer: 3,
    explanation: '`:reload` (or `:r`) reloads the previously loaded file. GHCi does not auto-detect file changes.',
  },
  {
    type: 'mcq',
    text: 'What is wrong with this snippet under Haskell\'s layout rule?\n\na = 10\n  b = 20\nc = 30',
    options: [
      'Nothing, it\'s valid',
      'You can\'t define more than 2 vars',
      'b is indented more — not a top-level definition at the same column',
      'Lowercase names are not allowed',
    ],
    answer: 2,
    explanation: 'The layout rule requires all top-level definitions to start in the same column. Since `b` is indented further, Haskell treats it as a continuation of `a`, not a new definition.',
  },
  {
    type: 'mcq',
    text: 'What does this Haskell function compute?\n\nf [] = []\nf (x:xs) = f ys ++ [x] ++ f zs\n  where\n    ys = [a | a <- xs, a <= x]\n    zs = [b | b <- xs, b > x]',
    options: ['Reverses a list', 'Computes list length', 'Sorts a list (quicksort)', 'Filters even elements'],
    answer: 2,
    explanation: 'This is quicksort! It partitions around the head element x — elements ≤ x go left, elements > x go right — then recursively sorts each side.',
  },
  {
    type: 'mcq',
    text: 'Which of these is a valid Haskell function name?',
    options: ['MyFunc', '_myFunc', 'myFunc1', '1stFunc'],
    answer: 2,
    explanation: 'Function names must start with a lowercase letter. `MyFunc` starts with uppercase (reserved for types/constructors). `1stFunc` starts with a digit. `_myFunc` starting with underscore is allowed in some contexts but `myFunc1` is the cleanest valid example shown.',
  },
];
