export const questions = [
  {
    type: 'mcq',
    text: 'What is a type in Haskell?',
    options: [
      'A keyword for defining functions',
      'A collection of related values',
      'A module import statement',
      'A runtime tag on a value',
    ],
    answer: 1,
    explanation: 'A type is a collection of related values. For example, Bool contains True and False, and Int contains fixed-precision integers.',
  },
  {
    type: 'mcq',
    text: 'What does static type checking provide?',
    options: [
      'Faster runtime evaluation via JIT compilation',
      'Automatic garbage collection',
      'All type errors are found at compile time, removing runtime type checks',
      'Dynamic dispatch for overloaded operators',
    ],
    answer: 2,
    explanation: 'Static type checking finds all type errors at compile time, making programs safer and faster by removing the need for type checks at run time.',
  },
  {
    type: 'mcq',
    text: 'Which syntax is used to annotate an expression e with type T in Haskell?',
    options: ['e -> T', 'e : T', 'e :: T', 'T e'],
    answer: 2,
    explanation: 'Type annotations are written as `e :: T`. For example, `True :: Bool` or `(5 + 5) :: Int`.',
  },
  {
    type: 'mcq',
    text: 'What is the type of `String` in Haskell?',
    options: ['String', 'Char', '[Char]', 'Text'],
    answer: 2,
    explanation: 'String is a type synonym for [Char] — it is defined as `type String = [Char]`.',
  },
  {
    type: 'tf',
    text: 'The type of a list in Haskell encodes its length.',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. The type of a list says nothing about its length. `[Bool]` could be a list of 0, 1, or any number of Bool values.',
  },
  {
    type: 'mcq',
    text: 'What distinguishes a tuple type from a list type in Haskell?',
    options: [
      'Tuples can only hold numbers',
      'The tuple type encodes both its size and the types of each component',
      'Lists encode their length in the type, tuples do not',
      'Tuples require all elements to be the same type',
    ],
    answer: 1,
    explanation: 'A tuple type encodes its size and the type of each component. E.g., `(Bool, Char, Bool)` is a 3-tuple with those specific types. Lists only encode the element type.',
  },
  {
    type: 'mcq',
    text: 'What is the type of `add (x,y) = x + y` where both arguments are Int?',
    options: ['Int -> Int -> Int', '(Int, Int) -> Int', 'Int -> Int', 'Num a => a -> a -> a'],
    answer: 1,
    explanation: '`add :: (Int, Int) -> Int` — it takes a single tuple argument containing two Ints and returns an Int.',
  },
  {
    type: 'mcq',
    text: 'What is the key property of a curried function?',
    options: [
      'It takes all arguments as a tuple',
      'It takes arguments one at a time, returning a function after each',
      'It uses lazy evaluation exclusively',
      'It requires explicit type annotations',
    ],
    answer: 1,
    explanation: 'A curried function takes its arguments one at a time, returning a new function after each. `add\' :: Int -> Int -> Int` takes x and returns a function that takes y.',
  },
  {
    type: 'mcq',
    text: 'How does the type arrow `->` associate in Haskell?',
    options: ['Left', 'Right', 'Neither — it is non-associative', 'Depends on context'],
    answer: 1,
    explanation: '`->` associates to the right. So `Int -> Int -> Int -> Int` means `Int -> (Int -> (Int -> Int))`.',
  },
  {
    type: 'mcq',
    text: 'How does function application associate in Haskell?',
    options: ['Right', 'Left', 'Neither — it is non-associative', 'Depends on precedence'],
    answer: 1,
    explanation: 'Function application associates to the left. So `mult x y z` means `((mult x) y) z`.',
  },
  {
    type: 'tf',
    text: '`add\' 1` is a valid Haskell expression if `add\' :: Int -> Int -> Int`, and it has type `Int -> Int`.',
    options: ['True', 'False'],
    answer: 0,
    explanation: 'True. Partially applying `add\'` with one argument yields a new function `Int -> Int`. This is a key benefit of currying.',
  },
  {
    type: 'mcq',
    text: 'What does it mean for a function to be polymorphic?',
    options: [
      'It can be defined in multiple modules',
      'Its type contains one or more type variables, making it work with many types',
      'It has multiple implementations selected at runtime',
      'It uses pattern matching on its arguments',
    ],
    answer: 1,
    explanation: 'A polymorphic function has type variables in its type signature. `length :: [a] -> Int` works for lists of any element type `a`.',
  },
  {
    type: 'mcq',
    text: 'What is the type of `id` in Haskell?',
    options: ['Int -> Int', 'a -> a', 'a -> b', '() -> ()'],
    answer: 1,
    explanation: '`id :: a -> a` — for any type `a`, the identity function maps a value of type `a` to itself.',
  },
  {
    type: 'mcq',
    text: 'What convention governs type variable names in Haskell?',
    options: [
      'Must be uppercase, e.g., A, B, C',
      'Must start with lowercase, usually a, b, c, etc.',
      'Must be single characters only',
      'Must be prefixed with t_, e.g., t_a',
    ],
    answer: 1,
    explanation: 'Type variables must begin with a lower-case letter and are usually named a, b, c, etc.',
  },
  {
    type: 'mcq',
    text: 'A polymorphic function is called overloaded when:',
    options: [
      'It has more than three arguments',
      'Its type contains one or more class constraints',
      'It is defined in multiple modules',
      'It operates on tuples',
    ],
    answer: 1,
    explanation: 'An overloaded function has class constraints in its type. For example, `sum :: Num a => [a] -> a` — the `Num a` constraint restricts `a` to numeric types.',
  },
  {
    type: 'mcq',
    text: 'What does the `Eq` type class provide?',
    options: [
      'Arithmetic operators (+, -, *)',
      'Ordering operators (<, >, <=, >=)',
      'Equality and inequality operators (==, /=)',
      'Conversion to and from strings',
    ],
    answer: 2,
    explanation: 'The `Eq` class provides `(==) :: Eq a => a -> a -> Bool` and `(/=) :: Eq a => a -> a -> Bool`.',
  },
  {
    type: 'mcq',
    text: 'What does the `Ord` type class require?',
    options: [
      'Only that `show` is defined for a type',
      'That `Eq` is already satisfied, then adds ordering comparisons',
      'That a type is numeric',
      'That a type can be enumerated',
    ],
    answer: 1,
    explanation: '`class (Eq a) => Ord a` — `Ord` extends `Eq`, requiring equality first, then adding `compare`, `<`, `<=`, `>`, `>=`, `min`, and `max`.',
  },
  {
    type: 'mcq',
    text: 'What does `show :: a -> String` (from the Show class) do?',
    options: [
      'Reads a value from a String',
      'Converts a value to its String representation',
      'Displays a value on screen with a newline',
      'Serializes a value to binary',
    ],
    answer: 1,
    explanation: '`show` converts a value to its String representation. For example, `show 10` returns `"10"` and `show [1,2,3]` returns `"[1,2,3]"`.',
  },
  {
    type: 'tf',
    text: 'The expression `sum [\'a\',\'b\',\'c\']` is valid in Haskell because `sum` is polymorphic.',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. `sum :: Num a => [a] -> a` requires `a` to be a numeric type. `Char` is not in the `Num` class, so this causes a type error.',
  },
  {
    type: 'mcq',
    text: 'According to the lecture, what is good practice when defining a new function in Haskell?',
    options: [
      'Always use `let` bindings instead of `where`',
      'Begin by writing down its type before implementing it',
      'Define it inline using lambda syntax first',
      'Test it in GHCi before adding a type signature',
    ],
    answer: 1,
    explanation: 'The lecture states: "When defining a new function in Haskell, it is useful to begin by writing down its type." Stating types within a script is also good practice.',
  },
];
