export const questions = [
  // ── IO ────────────────────────────────────────────────────────────────
  {
    type: 'mcq',
    text: 'What is the conceptual type of `IO a` in Haskell?',
    options: [
      'a -> IO a',
      'World -> (a, World)',
      '(a, World) -> World',
      'IO -> a',
    ],
    answer: 1,
    explanation: 'IO a is conceptually `World -> (a, World)`. An IO action takes the current world state, performs effects, and returns a result value of type a alongside a new world state.',
  },
  {
    type: 'mcq',
    text: 'What is the type of `putChar`?',
    options: [
      'IO Char',
      'Char -> IO Char',
      'Char -> IO ()',
      'String -> IO ()',
    ],
    answer: 2,
    explanation: '`putChar :: Char -> IO ()`. It takes a Char, writes it to the screen, and returns the empty tuple () — indicating it has a side effect but no meaningful return value.',
  },
  {
    type: 'mcq',
    text: 'What does `return` do in Haskell?',
    options: [
      'Exits the current function immediately',
      'Wraps a pure value into a monadic context with no side effects',
      'Reads a value from IO and returns it',
      'Equivalent to throwing an exception',
    ],
    answer: 1,
    explanation: '`return :: a -> IO a` (or `a -> m a` generally) wraps a pure value in a monad. It does NOT exit the function. `return 5` in a do block just produces `IO Int` with value 5 and no effects.',
  },
  {
    type: 'tf',
    text: 'In do notation, every line must bind its result with `<-`.',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. Lines that produce results you want to use are bound with `<-`. Lines whose results you want to discard are written as bare actions (e.g., `putStrLn "hello"` without binding).',
  },
  {
    type: 'mcq',
    text: 'What is the desugared form of:\n\ndo x <- a1\n   y <- a2\n   return (x + y)',
    options: [
      'a1 >> a2 >> return',
      'a1 >>= \\x -> a2 >>= \\y -> return (x + y)',
      'bind a1 (bind a2 (return))',
      'a1 <*> a2 >>= return',
    ],
    answer: 1,
    explanation: 'do notation is syntactic sugar for nested >>=. Each `v <- action` becomes `action >>= \\v -> ...`. The entire block becomes `a1 >>= \\x -> a2 >>= \\y -> return (x + y)`.',
  },
  {
    type: 'mcq',
    text: 'What does `getLine` return when the user types "hello" and presses Enter?',
    options: [
      '"hello\\n"',
      '"hello"',
      '["h","e","l","l","o"]',
      'IO "hello"',
    ],
    answer: 1,
    explanation: 'getLine reads characters until `\\n` and returns them as a String, EXCLUDING the newline. The result is the String "hello" (type IO String, value "hello").',
  },
  {
    type: 'mcq',
    text: 'What is the type of `main` in a Haskell program?',
    options: [
      'IO String',
      'IO Int',
      'IO ()',
      'String -> IO ()',
    ],
    answer: 2,
    explanation: '`main :: IO ()`. A complete Haskell program is a single IO action. main must have type `IO ()` — it performs effects but returns no meaningful value.',
  },
  // ── FUNCTORS ──────────────────────────────────────────────────────────
  {
    type: 'mcq',
    text: 'What is the type of `fmap`?',
    options: [
      '(a -> b) -> a -> b',
      '(a -> b) -> f a -> f b',
      'f (a -> b) -> f a -> f b',
      '(a -> b) -> [a] -> [b]',
    ],
    answer: 1,
    explanation: '`fmap :: (a -> b) -> f a -> f b`. It takes a pure function and a wrapped value, applies the function inside the structure, and returns the same structure with the result. The shape of `f` is preserved.',
  },
  {
    type: 'mcq',
    text: 'What does `fmap not (Just True)` return?',
    options: [
      'Just True',
      'Nothing',
      'Just False',
      'False',
    ],
    answer: 2,
    explanation: 'The Maybe Functor instance applies the function to the wrapped value: `fmap not (Just True) = Just (not True) = Just False`. The Just wrapper is preserved.',
  },
  {
    type: 'mcq',
    text: 'What does `fmap (+1) Nothing` return?',
    options: [
      'Just 1',
      'Nothing',
      '0',
      'Error — cannot fmap over Nothing',
    ],
    answer: 1,
    explanation: 'The Maybe Functor instance: `fmap _ Nothing = Nothing`. The function is completely ignored — Nothing maps to Nothing regardless of the function.',
  },
  {
    type: 'mcq',
    text: 'What does `fmap (+1) (Node (Leaf 1) (Leaf 2))` return, given the Tree Functor instance?',
    options: [
      'Leaf 3',
      'Node (Leaf 1) (Leaf 2)',
      'Node (Leaf 2) (Leaf 3)',
      'Node (Leaf 2) (Leaf 2)',
    ],
    answer: 2,
    explanation: 'The Tree Functor applies the function to each Leaf: `fmap g (Node l r) = Node (fmap g l) (fmap g r)` and `fmap g (Leaf x) = Leaf (g x)`. So (+1) is applied to both leaves: Node (Leaf 2) (Leaf 3).',
  },
  {
    type: 'mcq',
    text: 'Which two functor laws must every Functor instance satisfy?',
    options: [
      'fmap id = id   and   fmap (g . h) = fmap g . fmap h',
      'fmap pure = id   and   fmap (f . g) = fmap f >> fmap g',
      'fmap id = pure   and   fmap f . fmap g = fmap (f >> g)',
      'fmap return = id   and   fmap f = f',
    ],
    answer: 0,
    explanation: 'Law 1 (identity): mapping id changes nothing. Law 2 (composition): mapping a composition equals composing the maps. These ensure fmap is a genuine "structure-preserving" map.',
  },
  // ── APPLICATIVES ──────────────────────────────────────────────────────
  {
    type: 'mcq',
    text: 'Why are Applicatives needed if we already have Functors?',
    options: [
      'Functors only work on lists; Applicatives work on all types',
      'fmap only lifts single-argument functions; Applicatives handle multi-argument functions',
      'Applicatives are faster than Functors',
      'Functors cannot handle Nothing; Applicatives can',
    ],
    answer: 1,
    explanation: '`fmap :: (a -> b) -> f a -> f b` only works for functions of one argument. For `(+) :: Int -> Int -> Int` you need `<*>` which applies a wrapped function `f (a -> b)` to a wrapped value `f a`.',
  },
  {
    type: 'mcq',
    text: 'What does `pure (+) <*> Just 2 <*> Just 3` return?',
    options: [
      'Just 2',
      'Nothing',
      'Just 5',
      'Just (2,3)',
    ],
    answer: 2,
    explanation: '`pure (+)` wraps (+) in Just. `Just (+) <*> Just 2 = Just (+2)` (partial application). `Just (+2) <*> Just 3 = Just 5`. One Nothing anywhere would make the whole result Nothing.',
  },
  {
    type: 'mcq',
    text: 'What does `pure (+) <*> [1,3] <*> [2,5]` return?',
    options: [
      '[3,8]',
      '[3,6,5,8]',
      '[1,3,2,5]',
      '[6,15]',
    ],
    answer: 1,
    explanation: 'List <*> is a Cartesian product: each function applied to each value. (+1) applied to [2,5] gives [3,6]; (+3) applied to [2,5] gives [5,8]. Combined: [3,6,5,8].',
  },
  {
    type: 'mcq',
    text: 'What does `[(*2), (+3)] <*> [1,2,3]` return?',
    options: [
      '[2,5,4,5,6,6]',
      '[2,3,4,5,6,6]',
      '[2,4,6,4,5,6]',
      '[3,4,5,2,4,6]',
    ],
    answer: 2,
    explanation: 'Each function is applied to every element: (*2) applied to [1,2,3] gives [2,4,6]; (+3) applied to [1,2,3] gives [4,5,6]. The results are concatenated: [2,4,6,4,5,6].',
  },
  {
    type: 'mcq',
    text: 'What is the relationship between fmap, pure, and <*>?',
    options: [
      'fmap g x = pure g >> x',
      'fmap g x = pure g <*> x',
      'pure g = fmap g <*> x',
      'fmap g x = g <*> pure x',
    ],
    answer: 1,
    explanation: '`fmap g x = pure g <*> x`. This is also written `g <$> x`. It shows that fmap is a special case of <*> where the function is pure (unwrapped). <$> is just infix fmap.',
  },
  // ── MONADS ────────────────────────────────────────────────────────────
  {
    type: 'mcq',
    text: 'What is the type of `>>=` (bind)?',
    options: [
      'm a -> m b -> m (a, b)',
      'm a -> (a -> m b) -> m b',
      '(a -> m b) -> m a -> m b',
      'm (a -> b) -> m a -> m b',
    ],
    answer: 1,
    explanation: '`(>>=) :: m a -> (a -> m b) -> m b`. It takes a computation that yields `a`, and a function that takes that `a` and produces a new computation yielding `b`. The result of the first feeds into the second.',
  },
  {
    type: 'mcq',
    text: 'What does `Just 10 >>= div2 >>= div2` return, where `div2 x = if even x then Just (x `div` 2) else Nothing`?',
    options: [
      'Just 2',
      'Just 5',
      'Nothing',
      'Just 10',
    ],
    answer: 2,
    explanation: 'Just 10 >>= div2 = Just 5 (10 is even). Just 5 >>= div2 = Nothing (5 is odd). Once Nothing is produced, `Nothing >>= _ = Nothing` — the chain short-circuits.',
  },
  {
    type: 'mcq',
    text: 'What does the Maybe Monad instance do when it encounters Nothing on the left of >>=?',
    options: [
      'Applies the function to a default value',
      'Throws a runtime exception',
      'Returns Nothing without applying the function',
      'Skips to the next Just in the chain',
    ],
    answer: 2,
    explanation: '`Nothing >>= _ = Nothing`. The function is completely ignored — Nothing propagates through the entire chain. This is how Maybe models "fail fast" computations.',
  },
  {
    type: 'mcq',
    text: 'What does `pairs [1,2] [3,4]` return, given:\n\npairs xs ys = do x <- xs\n               y <- ys\n               return (x,y)',
    options: [
      '[(1,3),(2,4)]',
      '[(1,2),(3,4)]',
      '[(1,3),(1,4),(2,3),(2,4)]',
      '[(1,4),(2,3)]',
    ],
    answer: 2,
    explanation: 'The list monad `xs >>= f = [y | x <- xs, y <- f x]` produces all combinations. For each x in [1,2] and each y in [3,4], return (x,y) gives the full Cartesian product: [(1,3),(1,4),(2,3),(2,4)].',
  },
  // ── MONAD LAWS ────────────────────────────────────────────────────────
  {
    type: 'mcq',
    text: 'Which statement correctly expresses the Left Identity monad law?',
    options: [
      'mx >>= return = mx',
      'return x >>= f = f x',
      '(mx >>= f) >>= g = mx >>= (f >>= g)',
      'return (f x) = fmap f (return x)',
    ],
    answer: 1,
    explanation: 'Left Identity: `return x >>= f = f x`. Wrapping x with return then immediately binding with f is the same as just applying f to x directly. return has no computational effect.',
  },
  {
    type: 'mcq',
    text: 'Which statement correctly expresses the Right Identity monad law?',
    options: [
      'return x >>= f = f x',
      'mx >>= return = mx',
      'fmap return mx = mx',
      'mx >> return = pure mx',
    ],
    answer: 1,
    explanation: 'Right Identity: `mx >>= return = mx`. Feeding a monadic computation into return (which just wraps the value) produces the same computation. return does nothing computationally.',
  },
  // ── HIERARCHY ─────────────────────────────────────────────────────────
  {
    type: 'mcq',
    text: 'What is the correct typeclass hierarchy?',
    options: [
      'Monad → Applicative → Functor',
      'Functor → Applicative → Monad',
      'Applicative → Functor → Monad',
      'They are independent — no hierarchy',
    ],
    answer: 1,
    explanation: 'Functor is the most general. Applicative extends Functor (adds <*> and pure). Monad extends Applicative (adds >>= and return). Every Monad is an Applicative; every Applicative is a Functor.',
  },
  {
    type: 'mcq',
    text: 'What is the key difference between Applicative and Monad?',
    options: [
      'Applicative works on lists; Monad works on Maybe',
      'Monad allows the result of one computation to affect the structure of the next; Applicative cannot',
      'Applicative supports do notation; Monad uses <*>',
      'There is no practical difference',
    ],
    answer: 1,
    explanation: 'In Applicative, the structure of computations is fixed upfront — `f <*> x` cannot let x\'s result change what f does. In Monad, `mx >>= f` lets the value inside mx determine what computation `f` produces next.',
  },
]
