export const questions = [
  {
    type: 'mcq',
    text: 'What does the following evaluate to?\n\nf True _ = 1\nf _ True = 2\nf _ _    = 3\n\nf True True',
    options: ['2', '3', '1', 'Error — overlapping patterns'],
    answer: 2,
    explanation: 'Pattern matching is tried top to bottom. The first equation `f True _ = 1` matches immediately because the first argument is True and `_` matches anything. Result: 1.',
  },
  {
    type: 'tf',
    text: 'In Haskell, patterns in a function definition may repeat variables — e.g., `f x x = True` is valid.',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. Patterns may NOT repeat variables. `f x x = True` is illegal. To check equality you must use a guard: `f x y | x == y = True`.',
  },
  {
    type: 'mcq',
    text: 'What does `foldr (:) [] [1,2,3]` return?',
    options: ['[3,2,1]', '[]', '[1,2,3]', 'Error — (:) takes wrong arguments'],
    answer: 2,
    explanation: 'foldr replaces each (:) with (:) and [] with []. So 1:(2:(3:[])) stays [1,2,3]. This is the identity behaviour — foldr (:) [] is the list identity.',
  },
  {
    type: 'mcq',
    text: 'What is the key difference between `let` and `where`?',
    options: [
      'let is only for numeric bindings; where works for all types',
      'let...in is an expression; where is a declaration attached to an equation',
      'where is evaluated eagerly; let is lazy',
      'They are completely interchangeable in all contexts',
    ],
    answer: 1,
    explanation: '`let...in` is an expression and can appear anywhere an expression is expected. `where` is a declaration block scoped to the equation it belongs to — it cannot appear inside an expression directly.',
  },
  {
    type: 'mcq',
    text: 'What does `map (*2) (filter odd [1..5])` return?',
    options: ['[2,4,6,8,10]', '[1,3,5]', '[2,6,10]', '[1,2,3,4,5]'],
    answer: 2,
    explanation: 'filter odd [1..5] = [1,3,5]. Then map (*2) [1,3,5] = [2,6,10].',
  },
  {
    type: 'mcq',
    text: 'What does the section `(2/)` produce when applied to 8?',
    options: ['4.0', '0.25', '16.0', '6.0'],
    answer: 1,
    explanation: '`(2/)` is a section that fixes the LEFT argument: it computes `2 / x`. So `(2/) 8 = 2/8 = 0.25`. Compare with `(/2)` which halves its argument.',
  },
  {
    type: 'mcq',
    text: 'What does `foldr (\\x acc -> acc ++ [x]) [] [1,2,3]` return?',
    options: ['[1,2,3]', '[3,2,1]', '[[1],[2],[3]]', 'Error'],
    answer: 1,
    explanation: 'This foldr appends each element to the END of the accumulator, building the list in reverse. Expanding right-to-left: the last element 3 gets placed first. Result: [3,2,1]. This is one way to define reverse with foldr.',
  },
  {
    type: 'mcq',
    text: 'What is the result of `foldl (-) 0 [1,2,3]`?',
    options: ['6', '-6', '0', '-4'],
    answer: 1,
    explanation: 'foldl is left-associative: ((0-1)-2)-3 = (-1-2)-3 = (-3)-3 = -6.',
  },
  {
    type: 'tf',
    text: '`head` is a total function — it is defined for all possible list inputs.',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. `head` is a partial function. It is undefined on the empty list — `head []` throws a runtime exception. A total function must map every element in its domain to a result.',
  },
  {
    type: 'mcq',
    text: 'How many pairs does this comprehension produce?\n\n[(x,y) | x <- [1..3], y <- [1..x]]',
    options: ['3', '9', '6', '4'],
    answer: 2,
    explanation: 'When x=1: y<-[1..1] gives 1 pair. When x=2: y<-[1..2] gives 2 pairs. When x=3: y<-[1..3] gives 3 pairs. Total: 1+2+3 = 6. This is a dependent generator — y depends on x.',
  },
  {
    type: 'mcq',
    text: 'Which of these is a higher-order function?',
    options: [
      'length :: [a] -> Int',
      'not :: Bool -> Bool',
      'twice :: (a -> a) -> a -> a',
      'reverse :: [a] -> [a]',
    ],
    answer: 2,
    explanation: '`twice` takes a function `(a -> a)` as its first argument — that makes it higher-order. The others only take values (lists, Bool, etc.), not functions.',
  },
  {
    type: 'mcq',
    text: 'What does `takeWhile even [2,4,5,6,8]` return?',
    options: ['[2,4,6,8]', '[2,4]', '[5,6,8]', '[]'],
    answer: 1,
    explanation: 'takeWhile selects elements from the front while the predicate holds. It stops the moment 5 fails `even`. Result: [2,4].',
  },
  {
    type: 'mcq',
    text: 'What does `(f . g) x` mean?',
    options: ['f x applied to g', 'f (g x)', 'g (f x)', 'f multiplied by g, then applied to x'],
    answer: 1,
    explanation: 'Function composition: `(f . g) x = f (g x)`. g is applied first, then f is applied to the result. The dot operator chains functions right-to-left.',
  },
  {
    type: 'mcq',
    text: 'What does `filter (not . even) [1..6]` return?',
    options: ['[2,4,6]', '[1,2,3,4,5,6]', '[1,3,5]', '[]'],
    answer: 2,
    explanation: '`not . even` is a composed predicate that returns True when even returns False. So it keeps only odd numbers. Result: [1,3,5].',
  },
  {
    type: 'mcq',
    text: 'What does `zip [1,2,3] "ab"` return?',
    options: ['[(1,\'a\'),(2,\'b\'),(3,\' \')]', 'Error — lists differ in length', '[(1,\'a\'),(2,\'b\')]', '[(\'a\',1),(\'b\',2)]'],
    answer: 2,
    explanation: 'zip stops at the end of the shorter list. [1,2,3] has length 3, "ab" has length 2, so result is [(1,\'a\'),(2,\'b\')].',
  },
  {
    type: 'mcq',
    text: 'What does `[x^2 | x <- [1..5], odd x]` return?',
    options: ['[1,4,9,16,25]', '[2,4]', '[1,9,25]', '[4,16]'],
    answer: 2,
    explanation: 'The guard `odd x` filters to x = 1, 3, 5. Squaring gives 1, 9, 25. Result: [1,9,25].',
  },
  {
    type: 'tf',
    text: '`otherwise` is a special keyword built into the Haskell compiler.',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. `otherwise` is simply defined in the Prelude as `otherwise = True`. It is a regular value — not a keyword — that makes the last guard always match.',
  },
  {
    type: 'mcq',
    text: 'Which is the correct `foldr` definition of `length`?\n\nlength = foldr (???) 0',
    options: [
      '(\\x n -> n)',
      '(\\x n -> n + 1)',
      '(\\_ n -> 1 + n)',
      '(\\x n -> x + n)',
    ],
    answer: 2,
    explanation: 'length counts elements regardless of value, so the element is ignored with `_`. Each step adds 1 to the accumulator n. `length [1,2,3] = 1+(1+(1+0)) = 3`.',
  },
  {
    type: 'mcq',
    text: 'Why does `factorial (-1)` diverge?',
    options: [
      'Negative numbers are not in scope for Int',
      'The base case `factorial 0 = 1` is never reached — n decreases without bound',
      'Haskell only supports natural number recursion',
      'Pattern matching fails on negative integers',
    ],
    answer: 1,
    explanation: 'factorial n = n * factorial (n-1) keeps decrementing: (-1), (-2), (-3), ... The base case 0 is never hit, so the recursion never terminates.',
  },
  {
    type: 'mcq',
    text: 'What is the type of `foldr`?',
    options: [
      '(a -> b) -> [a] -> b',
      '(a -> b -> b) -> b -> [a] -> b',
      '(b -> a -> b) -> b -> [a] -> b',
      '(a -> a -> a) -> [a] -> a',
    ],
    answer: 1,
    explanation: '`foldr :: (a -> b -> b) -> b -> [a] -> b`. The combining function takes the current element (a) and accumulator (b) and returns a new (b). The second arg is the base value, third is the list.',
  },
  {
    type: 'mcq',
    text: 'Given `qsort (x:xs)` with input [3,1,2], what are `smaller` and `larger`?',
    options: [
      'smaller=[1,2], larger=[]',
      'smaller=[], larger=[1,2]',
      'smaller=[1], larger=[2]',
      'smaller=[3], larger=[1,2]',
    ],
    answer: 0,
    explanation: 'pivot=3. smaller=[a|a<-[1,2], a<=3]=[1,2]. larger=[b|b<-[1,2], b>3]=[]. Then: qsort [1,2] ++ [3] ++ qsort [].',
  },
  {
    type: 'tf',
    text: 'The expression `(\\x -> (\\y -> x + y)) 3 4` evaluates to 7.',
    options: ['True', 'False'],
    answer: 0,
    explanation: 'True. `\\x -> (\\y -> x+y)` is a curried addition. Applying to 3 gives `\\y -> 3+y`. Applying that to 4 gives 7. This is how all multi-argument lambdas work.',
  },
  {
    type: 'mcq',
    text: 'What does `concat [[1,2],[3],[4,5,6]]` return, given:\n\nconcat xss = [x | xs <- xss, x <- xs]',
    options: ['[[1,2],[3],[4,5,6]]', '[1,2,3,4,5,6]', '[1,3,4]', 'Error'],
    answer: 1,
    explanation: 'The outer generator `xs <- xss` iterates over each sub-list. The inner generator `x <- xs` iterates over each element in that sub-list. Together they flatten the list of lists to [1,2,3,4,5,6].',
  },
  {
    type: 'mcq',
    text: 'What is `any (>10) [1..9]`?',
    options: ['True', 'False', 'Error', '0'],
    answer: 1,
    explanation: '`any` returns True if at least one element satisfies the predicate. No element in [1..9] exceeds 10, so all fail the test. Result: False.',
  },
  {
    type: 'mcq',
    text: 'What does `dropWhile (<3) [1,2,3,4,1]` return?',
    options: ['[3,4,1]', '[1,2]', '[3,4]', '[4,1]'],
    answer: 0,
    explanation: 'dropWhile removes elements from the front while the predicate holds. 1 and 2 satisfy (<3) so they are dropped. 3 fails (<3), so it and everything after is kept: [3,4,1].',
  },
]
